name: Deploy Android
on:
  push:
    branches:
      - master
jobs:
  deploy-android:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Upload Key
        working-directory: ./android/app
        run: echo ${{ secrets.UPLOAD_KEY }} | base64 -d >> my-upload-key.keystore

      - name: Get Service Account Config
        working-directory: ./android
        run: echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 -d >> api.json

      - name: Install Packages
        run: yarn --frozen-lockfile

      - name: OPTIONAL Jetify
        run: npx jetify
        
      - name: Compile and Upload
        uses: maierj/fastlane-action@v2.184.1
        with:
          lane: "deploy_alpha"
          subdirectory: "android"
        env:
          MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
